---
# system packages to install
pkgs_to_install:
  - ca-certificates
  - cmake
  - containerd.io
  - curl
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - emacs28-nativecomp
  - gcc
  - gnome-tweaks
  - gnupg
  - gtimelog
  - isync
  - libvterm-dev
  - lsb-release
  - maildir-utils
  - make
  - msmtp
  - mu4e
  - papirus-icon-theme

# system packages to remove
pkgs_to_remove:
  - geary

# flatpaks
flatpaks:
  - com.github.tchx84.Flatseal
  - com.bitwarden.desktop
  - org.zotero.Zotero
  - io.dbeaver.DBeaverCommunity

# repos (ppa)
ppa:
  - repo: "ppa:ubuntu-elisp/ppa"
    codename: "jammy"
  - repo: "ppa:yubico/stable"
    codename: "jammy"
  - repo: "ppa:papirus/papirus"
    codename: "jammy"

# repos (non-ppa)
non_ppa:
  - filename: "signal"
    key_location: "https://updates.signal.org/desktop/apt/keys.asc"
    repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
  - filename: "docker"
    key_location: "https://download.docker.com/linux/ubuntu/gpg"
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
  - filename: "element"
    key_location: "https://packages.element.io/debian/element-io-archive-keyring.gpg"
    repo: "deb https://packages.element.io/debian/ default main"

# vpn
mullvad_account_number: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30343761376539633733663065323530323639633031613736353066373033643939333661373663
  3764383261343664633362303035376436666338666639350a303566636364656264393661346434
  39336137343262336639303766303533303735393939356533626365343962396137353363643966
  6138343034663133330a366132616531376662373933333738396563613335363663663530386634
  65383965383730343033363739663061643639333230653764663239323663326262

# fish > starship
starship_url: "https://github.com/starship/starship/releases/download/v1.10.2/starship-x86_64-unknown-linux-gnu.tar.gz"
starship_sha256sum: "253a62e48c1b15d5465c876560b71e1d3485697e22ab7adea85e37cbe1a70a54"

# fish > fisher plugins
fisher_plugins:
  - jethrokuan/z
  - jethrokuan/fzf
  - 2m/fish-history-merge
