---
- name: Get the username running the deploy
  become: false
  local_action: command whoami
  register: local_user

- name: Change user shell to zsh
  user:
    name: "{{ local_user.stdout }}"
    shell: /bin/zsh

- name: Get oh-my-zsh
  become: false
  shell: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  ignore_errors: true

- name: Remove exisinting files
  become: false
  file:
    path: "/home/{{ local_user.stdout }}/.zshrc"
    state: absent
  ignore_errors: true

- name: Install zsh-autosuggestions
  become: false
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ local_user.stdout }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1
  ignore_errors: true

- name: Install zsh-syntax-highlighting
  become: false
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: "/home/{{ local_user.stdout }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1
  ignore_errors: true

- name: Symlink relevant config files to playbook-workstation
  become: false
  file:
    src: "/home/{{ local_user.stdout }}/Projects/playbook-workstation/roles/ansible-zsh/files/.zshrc"
    dest: "/home/{{ local_user.stdout }}/.zshrc"
    state: link
