---
- name: Install base packages
  hosts: all
  tasks:
    - name: run roles/ansible-pkgs
      include_role:
        name: ansible-pkgs
  tags:
    - pkgs

- name: Enable backups
  hosts: all
  become: true
  tasks:
    - name: run roles/ansible-borgbackup
      include_role:
        name: ansible-borgbackup
  tags:
    - backup

- name: Setup shell
  hosts: all
  become: true
  tasks:
    - name: run roles/ansible-zsh
      include_role:
        name: ansible-zsh
  tags:
    - zsh
    - shell

- name: Setup (Doom) Emacs
  hosts: all
  tasks:
    - name: run roles/ansible-doom-emacs
      include_role:
        name: ansible-doom-emacs
  tags:
    - emacs

- name: Install mu4e
  hosts: all
  tasks:
    - name: run roles/ansible-mu4e
      include_role:
        name: ansible-mu4e
  tags:
    - emacs
    - mu4e

- name: Install Gnome Shell extensions
  hosts: all
  tasks:
    - name: run roles/ansible-gnome-extensions
      include_role:
        name: ansible-gnome-extensions
  tags:
    - gnome

- name: Customise Gnome
  hosts: all
  tasks:
    - name: run roles/ansible-gnome-config
      include_role:
        name: ansible-gnome-config
  tags:
    - gnome

- name: Mount CIFS and NFS shares
  hosts: all
  tasks:
    - name: run roles/ansible-mount
      include_role:
        name: ansible-mount
  tags:
    - mount
