---
- name: Install base packages
  hosts: all
  tasks:
    - name: run roles/ansible-pkgs
      include_role:
        name: ansible-pkgs
  tags:
    - pkgs

- name: Enable backups
  hosts: all
  become: true
  tasks:
    - name: run roles/ansible-borgbackup
      include_role:
        name: ansible-borgbackup
  tags:
    - backup

- name: Setup shell
  hosts: all
  become: true
  tasks:
    - name: run roles/ansible-shell
      include_role:
        name: ansible-shell
  tags:
    - shell

- name: Setup emacs
  hosts: all
  tasks:
    - name: run roles/ansible-emacs
      include_role:
        name: ansible-shell
  tags:
    - emacs
