---
- name: Install base packages
  hosts: all
  tasks:
    - name: run roles/ansible-pkgs
      include_role:
        name: ansible-pkgs
  tags:
    - pkgs

- name: Enable backups
  hosts: all
  become: true
  tasks:
    - name: run roles/ansible-borgbackup
      include_role:
        name: ansible-borgbackup
  tags:
    - backup

- name: Setup shell
  hosts: all
  become: true
  tasks:
    - name: run roles/ansible-shell
      include_role:
        name: ansible-shell
  tags:
    - shell

- name: Setup (Doom) Emacs
  hosts: all
  tasks:
    - name: run roles/ansible-doom-emacs
      include_role:
        name: ansible-doom-emacs
  tags:
    - emacs

- name: Install Gnome Shell extensions
  hosts: all
  tasks:
    - name: run roles/ansible-gnome-extensions
      include_role:
        name: ansible-gnome-extensions
  tags:
    - gnome
