---
- name: Get the username running the deploy
  become: false
  local_action: command whoami
  register: local_user

- name: Change user shell to zsh
  become: true
  user:
    name: "{{ local_user.stdout }}"
    shell: /bin/zsh

- name: Get oh-my-zsh
  become: false
  shell: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

- name: Remove exisinting files
  become: false
  file:
    path: "/home/{{ local_user.stdout }}/{{ item }}"
    state: absent
  loop:
    - .zshrc
    - .tool-versions
    - .default-python-packages
    - .default-npm-packages
    - .default-golang-pkgs

- name: Symlink relevant config files to playbook-workstation
  become: false
  file:
    src: "/home/{{ local_user.stdout }}/Projects/playbook-workstation/roles/ansible-shell/files/{{ item }}"
    dest: "/home/{{ local_user.stdout }}/{{ item }}"
    state: link
  loop:
    - .zshrc
    - .tool-versions
    - .default-python-packages
    - .default-npm-packages
    - .default-golang-pkgs

- name: Get asdf
  become: false
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: /home/lino/.asdf
    depth: 1

- name: Add asdf plugins
  become: false
  shell: "bash -c '/home/lino/.asdf/bin/asdf plugin add {{ item }}'"
  loop:
    - https://github.com/danhper/asdf-python
    - https://github.com/asdf-vm/asdf-nodejs
    - https://github.com/kennyp/asdf-golang
    - https://bitbucket.org/mgladdish/asdf-gohugo

- name: Add Node.js team to keyring
  become: false
  shell: "bash -c '/home/lino/.asdf/plugins/node/bin/import-release-team-keyring'"

- name: Install asdf languages
  become: false
  shell: "bash -c '/home/lino/.asdf/bin/asdf install {{ item }}'"
  loop:
    - python 3.9.2
    - nodejs lts
    - golang 1.16
    - gohugo extended_0.83.1
