---
- name: install base packages
  become: yes
  apt:
    pkg:
      - pass
      - webext-browserpass
      - apparmor-utils
      - apparmor-profiles
      - apparmor-profiles-extra
      - auditd
      - audispd-plugins
      - ufw

- name: fix bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928160 to run aa-genproof
  become: yes
  file: path={{ item }} state=touch
  with_items:
    - /etc/apparmor.d/local/usr.lib.dovecot.manageseive-login
    - /etc/apparmor.d/local/usr.lib.dovecot.auto
    - /etc/apparmor.d/local/usr.lib.dovecot.imap
    - /etc/apparmor.d/local/usr.lib.dovecot.anvil
    - /etc/apparmor.d/local/usr.sbin.dovecot
    - /etc/apparmor.d/local/usr.lib.dovecot.dovecot.deliver
    - /etc/apparmor.d/local/usr.lib.dovecot.dovecot.imap-login
    - /etc/apparmor.d/local/usr.lib.dovecot.pop3
    - /etc/apparmor.d/local/usr.lib.dovecot.dict
    - /etc/apparmor.d/local/usr.lib.dovecot.managesieve
    - /etc/apparmor.d/local/usr.lib.dovecot.dovecot-lda
    - /etc/apparmor.d/local/usr.lib.dovecot.ssl-params
    - /etc/apparmor.d/local/usr.lib.dovecot.dovecot-auth
    - /etc/apparmor.d/local/usr.lib.dovecot.log
    - /etc/apparmor.d/local/usr.lib.dovecot.pop3-login
    - /etc/apparmor.d/local/usr.lib.dovecot.config
