---
# TODO: Add emacs build dependencies
- name: install needed packages
  apt:
    pkg:
      - emacs
      - ripgrep
      - locate
      - fd-find
      - cmake
      - libtool
      - libtool-bin
      - libpng-dev
      - zlib1g-dev
      - libpoppler-glib-dev
      - libpoppler-private-dev
      - isync
      - libgmime-3.0-dev
      - libxapian-dev
      - guile-2.2-dev
      - html2text
      - xdg-utils
      - hunspell
      - hunspell-en-gb
      - hunspell-de-de
      - mit-scheme
      - sqlite3
      - texlive-base
      - texlive-font-utils
      - texlive-fonts-extra
      - texlive-humanities
      - texlive-science
      - texlive-lang-german
      - texlive-publishers
      - biber
      - latexmk
      - lmodern
      - graphviz
  become: yes
  tags:
    - packages

# TODO: build fejfighter/emacs pgtk-nativecomp branch from source (see old)
# TODO: adapt .desktop files for prefix

- name: sync fonts
  synchronize:
    src: fonts/
    dest: /home/lino/.local/share/fonts/

- name: refresh fonts cache
  shell: "fc-cache -f -v"

# - name: remove .emacs.d
#   shell: rm -rf /home/lino/.emacs.d

- name: clone doom emacs and private configuration
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    depth: "{{ item.depth }}"
    accept_hostkey: yes
  loop:
    - {
        repo: "https://github.com/hlissner/doom-emacs.git",
        dest: "~/.emacs.d",
        depth: 1,
      }
    - {
        repo: "git@gitlab.com:linozen/doom.git",
        dest: "~/.doom.d",
        depth: 1,
        accept_hostkey: yes,
      }
  tags:
    - emacs
    - doom

- name: install doom
  shell: "yes | ~/.emacs.d/bin/doom install"
  retries: 3
  delay: 1
  tags:
    - emacs
    - doom

- name: sync doom
  shell: "yes | ~/.emacs.d/bin/doom sync"
  retries: 3
  delay: 1
  tags:
    - emacs
    - doom

- name: copy emacs service to systemd directory
  become: yes
  copy:
    src: emacs.service
    dest: "/etc/systemd/user/emacs.service"

- name: enable emacs service
  service:
    name: emacs
    enabled: yes
    state: started
    user: yes

- name: Ensures ~/.local/share/applications
  file: path=/home/{{ remote_user }}/.local/share/applications state=directory
- name: copy emacs.desktop file
  copy:
    src: emacsclient.desktop
    dest: /home/lino/.local/share/applications/emacsclient.desktop
    mode: 0644

- name: copy org-protocol.desktop file
  copy:
    src: org-protocol.desktop
    dest: /home/lino/.local/share/applications/org-protocol.desktop
    mode: 0644

- name: associate org-protocol
  shell: "xdg-mime default org-protocol.desktop x-scheme-handler/org-protocol"
#
# not needed since it builds properly now
# - name: copy compiled vterm
#   copy:
#     src: vterm-module.so
#     dest: /home/lino/.emacs.d/.local/straight/build-27.1/vterm/vterm-module.so
