nodejs_version: "14.x"
npm_config_prefix: "/home/lino/.npm"
nodejs_npm_global_packages:
  - prettier
  - gatsby-cli
  - yarn
  - npx
  - create-react-app
  - pyright
  - bash-language-server
  - stylelint
  - js-beautify
