---
# List of NFS shares
nfs_share_mounts:
  - path: /home/lino/Syno/audio
    location: 192.168.178.11:/volume1/audio
  - path: /home/lino/Syno/video
    location: 192.168.178.11:/volume1/video
  - path: /home/lino/Syno/photo
    location: 192.168.178.11:/volume1/photo
  - path: /home/lino/Syno/share
    location: 192.168.178.11:/volume1/share
  - path: /home/lino/Syno/borg
    location: 192.168.178.11:/volume1/borg

nfs_version: 4
nfs_mount_opts: rsize=8192,wsize=8192,timeo=14,intr

# CIFS
samba_share_mounts:
  - path: /home/lino/Syno/archive
    location: //192.168.178.11/archive
