---
- name: ensure root has SSH key.
  become: yes
  user:
    name: "root"
    generate_ssh_key: yes
    ssh_key_file: "{{ ssh_key_file }}"
    ssh_key_type: ed25519
  register: root_user

- debug:
    var: root_user['ssh_public_key']

- name: ensure /etc/borgmatic exists
  become: yes
  file:
    path: /etc/borgmatic
    state: directory
    mode: 0700
    owner: root

- name: add config.yaml to /etc/borgmatic
  become: yes
  template:
    src: config.yaml.j2
    dest: "/etc/borgmatic/config.yaml"
    mode: 0600

- name: add root's ssh key to borgbase
  pause:
    prompt: "make sure root's public key is on borgbase"

- name: enter correct auth data into /etc/borgmatic/config.yaml
  pause:
    prompt: "make sure /etc/borgmatic/config.yaml is correct now that it's safe"

- name: make sure "sudo borgmatic runs fine"
  pause:
    prompt: "make sure the first 'sudo borgmatic runs fine'"

- name: add cron-job for borgmatic
  become: yes
  block:
    - name: add cron job for create, check and prune 5min before every hour
      cron:
        name: "borgmatic"
        minute: "55"
        hour: "*"
        day: "*"
        user: "root"
        cron_file: borgmatic
        job: "/usr/bin/borgmatic"

- name: set PATH for borgmatic cron job.
  become: yes
  cron:
    user: "root"
    cron_file: borgmatic
    name: PATH
    env: yes
    value: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
