---
- name: Create directories
  file:
    dest: "{{ pyenv_root | dirname }}"
    state: directory
- name: Clone pyenv repository
  git:
    repo: "{{ pyenv_repo }}"
    dest: "{{ pyenv_root }}"
    version: "{{ pyenv_version }}"
    update: "{{ pyenv_update }}"

- name: get some neat python stuff
  pip:
    name:
      - jupyterlab
      - docutils
      - black
      - python-language-server[all]
      - pyls-mypy
      - pyls-isort
      - pyls-black
    extra_args: --user
    executable: pip3
