---
# Do not create mountpoint using file, the mount module will create it
# automatically. This avoids problems where the module tries to change
# permissions on an existing directory

- name: Get the username running the deploy
  become: false
  local_action: command whoami
  register: local_user

- name: Mount nfs shares
  become: true
  mount:
    fstype: nfs
    state: mounted
    name: "{{ item.path }}"
    opts: "vers={{ nfs_version }},{{ nfs_mount_opts }}"
    src: "{{ item.location }}"
  with_items: "{{ nfs_share_mounts }}"

- name: Copy .smb to correct location
  become: true
  template:
    src: .smb.j2
    dest: "/root/.smb"
    mode: 0600

- name: Mount cifs shares
  become: true
  mount:
    fstype: cifs
    state: mounted
    path: "{{ item.path }}"
    opts: "credentials=/root/.smb,vers=3.0,uid={{ local_user.stdout}},forceuid,gid={{ local_user.stdout }},forcegid"
    src: "{{ item.location }}"
  with_items: "{{ samba_share_mounts }}"
