---
to_install:
  - autojump
  - biber
  - bleachbit
  - build-essential
  - chromium-browser
  - cifs-utils
  - cmake
  - containerd.io
  - cron
  - curl
  - dbus-user-session
  - dino-im
  - docker-ce
  - docker-ce-cli
  - docker-compose
  - emacs-snapshot
  - evolution
  - evolution-ews
  - exa
  - fd-find
  - fuse-overlayfs
  - fzf
  - graphviz
  - html2text
  - htop
  - hunspell
  - hunspell-de-de
  - hunspell-en-gb
  - isync
  - libnfs-utils
  - libssl-dev
  - maildir-utils
  - mu4e
  - nfs-common
  - openssh-server
  - pass
  - ripgrep
  - rsync
  - shellcheck
  - signal-desktop
  - slirp4netns
  - smbclient
  - sqlite3
  - syncthing
  - teams
  - texinfo
  - texlive-base
  - texlive-font-utils
  - texlive-fonts-extra
  - texlive-humanities
  - texlive-lang-german
  - texlive-publishers
  - texlive-science
  - torbrowser-launcher
  - ufw
  - uidmap
  - vlc
  - webext-keepassxc-browser
  - webext-ublock-origin-chromium
  - webext-ublock-origin-firefox
  - wget
  - xdg-utils
  - xdotool
  - yamllint
  - zotero
  - zsh

to_remove:
  - anthy
  - fcitx
  - fcitx-bin
  - fcitx-data
  - fcitx-modules
  - fcitx-table
  - fortune-mod
  - gnome-boxes
  - gnome-games
  - goldendict
  - hdate
  - hdate-applet
  - ibus-libpinyin
  - kasumi
  - khmerconverter
  - mlterm
  - mlterm-tiny
  - mozc-data
  - mozc-server
  - mozc-utils
  - rhythmbox
  - uim-mozc
  - xiterm+thai
  - xterm
  - geary
