---
- name: init mail database
  shell: "mu init --maildir {{ ansible_env.HOME }}/.mail --my-address=linus@sehn.tech --my-address=linus@fsfe.org && mu index"

- name: Symlink relevant config files to playbook-workstation
  file:
    src: "{{ ansible_env.HOME }}/Projects/playbook-workstation/roles/ansible-mu4e/files/.mbsyncrc"
    dest: "{{ ansible_env.HOME }}/.mbsyncrc"
    state: link
