- name: install base packages
  apt:
    pkg:
      - texinfo
      - libx11-dev
      - libxpm-dev
      - libjpeg-dev
      - libpng-dev
      - libgif-dev
      - libtiff-dev
      - libgtk-3-dev
      - libncurses-dev
      - libgnutls28-dev
      - libjansson-dev
      - shellcheck
  become: yes
  tags:
    - packages

- name: check, whether the /usr/bin/emacs exists
  stat:
    path: /usr/local/bin/emacs
  tags: emacs
  register: emacs_result

- name: extract emacs 27.1 into /tmp
  unarchive:
    src: https://ftp.gnu.org/pub/gnu/emacs/emacs-27.1.tar.gz
    dest: /tmp/
    remote_src: yes
  when: emacs_result.stat.exists == False

- name: configure emacs 27.1
  shell: ./configure chdir=/tmp/emacs-27.1
  when: emacs_result.stat.exists == False

- name: make
  shell: make chdir=/tmp/emacs-27.1
  when: emacs_result.stat.exists == False

- name: install emacs 27.1
  shell: make install chdir=/tmp/emacs-27.1
  become: yes
  become_user: root
  when: emacs_result.stat.exists == False

- name: remove tmp files used for emacs installation
  file: path={{ item }} state=absent
  with_items:
    - /tmp/emacs-27.1.tar.gz
    - /tmp/emacs-27.1
  when: emacs_result.stat.exists == False
