theme = "native"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
unit = "GiB"
format = "{free} {unit} free"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "networkmanager"
on_click = "foot fish -c 'nmtui'"
interface_name_exclude = ["virbr\\d+", "vnet0", "br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format=" {ssid} {strength}%"

[[block]]
block = "apt"
interval = 1800
format = "{count} updates available"
format_singular = "{count} update available"
critical_updates_regex = "(linux |linux-lts|linux-zen)"

[[block]]
block = "docker"
interval = 5
format = "{running}/{total} ({images})"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
per_core = false
format = "{barchart} {utilization}%"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°C"
chip = "thinkpad-isa-*"

[[block]]
block = "time"
interval = 60
format = "%R %A %d-%m-%y"

[[block]]
block = "battery"
interval = 10
full_format = "{percentage}"
format = "{percentage}% {time}"
