---
- name: Add third-party repository keys
  become: true
  apt_key:
    url: "{{ item.key_location }}"
    state: present
  loop: "{{ third_party_repos }}"

- name: Add third-party repositories
  become: true
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.filename }}"
    update_cache: true
  loop: "{{ third_party_repos }}"

- name: Run the equivalent of "apt-get update"
  become: true
  apt:
    update_cache: true

- name: Install base packages
  become: true
  apt:
    pkg:
      - acl
      - apparmor-profiles
      - apparmor-profiles-extra
      - apparmor-utils
      - audispd-plugins
      - auditd
      - autojump
      - biber
      - bleachbit
      - build-essential
      - calibre
      - chromium
      - cifs-utils
      - cmake
      - cron
      - curl
      - dino-im
      - dbus-user-session
      - fuse-overlayfs
      - slirp4netns
      - docker-compose
      - emacs-snapshot
      - evolution
      - evolution-ews
      - exa
      - fd-find
      - firefox-esr
      - fzf
      - graphviz
      - html2text
      - htop
      - hunspell
      - hunspell-de-de
      - hunspell-en-gb
      - isync
      - latexmk
      - libbz2-dev
      - libgmime-3.0-0
      - libgmime-3.0-dev
      - liblzma-dev
      - libnfs-utils
      - libpoppler-glib-dev
      - libpoppler-private-dev
      - libreoffice
      - libreoffice-gtk3
      - libsqlite3-dev
      - libtool
      - libtool-bin
      - libvirt-clients
      - libvirt-daemon-system
      - libxapian-dev
      - llvm
      - lm-sensors
      - lmodern
      - locales
      - locate
      - make
      - net-tools
      - nfs-common
      - ntp
      - openssh-client
      - papirus-icon-theme
      - pass
      - qemu-system
      - ripgrep
      - rsync
      - shellcheck
      - signal-desktop
      - smbclient
      - sqlite3
      - syncthing
      - syncthing-gtk
      - texinfo
      - texlive-base
      - texlive-font-utils
      - texlive-fonts-extra
      - texlive-humanities
      - texlive-lang-german
      - texlive-publishers
      - texlive-science
      - torbrowser-launcher
      - ufw
      - virt-manager
      - vlc
      - webext-keepassxc-browser
      - webext-debianbuttons
      - webext-ublock-origin-chromium
      - webext-ublock-origin-firefox
      - wget
      - xdg-utils
      - xdotool
      - yamllint
      - zotero
      - zsh

- name: Remove unnecessary packages
  become: true
  apt:
    state: absent
    pkg:
      - anthy
      - fcitx
      - fcitx-bin
      - fcitx-data
      - fcitx-modules
      - fcitx-table
      - fortune-mod
      - gnome-boxes
      - gnome-games
      - goldendict
      - hdate
      - hdate-applet
      - kasumi
      - khmerconverter
      - mlterm
      - mlterm-tiny
      - mozc-data
      - mozc-server
      - mozc-utils
      - rhythmbox
      - thunderbird
      - uim-mozc
      - xiterm+thai
      - xterm

- name: Remove useless packages from the cache
  become: true
  apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: true

- name: Copy syncthing user service to systemd directory
  become: true
  copy:
    src: syncthing.service
    dest: "/etc/systemd/user/syncthing.service"

- name: Enable syncthing user service
  service:
    name: syncthing
    enabled: true
    state: started
    scope: user

- name: Get Mullvad VPN Signing Key
  shell: "gpg2 --keyserver pool.sks-keyservers.net --recv-keys A1198702FC3E0A09A9AE5B75D5A1D4F266DE8DDF"

- name: Get Mullvad VPN client
  get_url:
    url: "https://mullvad.net/download/app/deb/latest"
    dest: "{{ ansible_env.HOME }}/Downloads"

- name: Get Mullvad VPN client signing key
  get_url:
    url: "https://mullvad.net/download/app/deb/latest/signature"
    dest: "{{ ansible_env.HOME }}/Downloads"

- name: Get Mullvad VPN Signing Key
  shell: "gpg2 --verify {{ ansible_env.HOME }}/Downloads/MullvadVPN-*.asc"

- name: Install Mullvad VPN client
  become: true
  shell: "yes | dpkg -i /home/lino/Downloads/Mullvad*.deb"

- name: Set Mullvad VPN account key
  become: true
  shell: "mullvad account set {{ mullvad_account_number }}"
