---
- name: Update packages
  become: yes
  apt:
    update_cache: yes

- name: Install base packages
  become: yes
  apt:
    pkg:
      # essentials
      - git
      - emacs
      - ansible
      - locales
      - build-essential
      - acl
      - ntp
      - htop
      - net-tools
      - zsh
      - fzf
      - exa
      - curl
      - make
      - wget
      - rsync
      - gnupg2
      - cron
      - borgbackup
      - borgmatic
      - llvm
      - openssh-client
      - pass
      - apparmor-utils
      - apparmor-profiles
      - apparmor-profiles-extra
      - auditd
      - audispd-plugins
      - ufw
      # browser
      - firefox-esr
      - torbrowser-launcher
      - webext-browserpass
      - webext-debianbuttons
      - webext-ublock-origin-firefox
      # mount stuff
      - cifs-utils
      - nfs-common
      - libnfs-utils
      - smbclient
      - cifs-utils
      # syncthing
      - syncthing
      - syncthing-gtk
      - vlc
      # virtualisation
      - qemu-system
      - libvirt-clients
      - libvirt-daemon-system
      - virt-manager
      # docker
      - docker.io
      - docker-clean
      - docker-compose
      # office
      - libreoffice
      - libreoffice-gtk3
      - calibre
      # monitoring
      - lm-sensors

- name: Remove unnecessary packages
  become: yes
  apt:
    state: absent
    pkg:
      - gnome-games
      - gnome-boxes
      - rhythmbox
      - xterm
      - mlterm
      - mlterm-tiny
      - fcitx
      - fcitx-table
      - fcitx-data
      - fcitx-modules
      - fcitx-bin
      - thunderbird
      - hdate
      - hdate-applet
      - xiterm+thai
      - khmerconverter
      - anthy
      - kasumi
      - goldendict
      - uim-mozc
      - mozc-utils
      - mozc-data
      - mozc-server
      - fortune-mod

- name: Remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Copy syncthing service to systemd directory
  become: yes
  copy:
    src: syncthing.service
    dest: "/etc/systemd/user/syncthing.service"

- name: Enable syncthing service
  service:
    name: syncthing
    enabled: yes
    state: started
    scope: user

- name: Set git e-mail
  git_config:
    name: user.email
    scope: global
    value: "linus@sehn.tech"

- name: Set git username
  git_config:
    name: user.name
    scope: global
    value: "linozen"
